class ChecksymData {
  ChecksymData(this.symptom);
  final String symptom;
}

final symptomList = [
  ChecksymData('Fever'),
  ChecksymData('Cough'),
  ChecksymData('Sore Throat'),
  ChecksymData('Breathless'),
  ChecksymData('Headache'),
  ChecksymData('Rash'),
  ChecksymData('Chills'),
  ChecksymData('Joint Pains'),
  ChecksymData('Myalgia'),
  ChecksymData('Diarrhea'),
  ChecksymData('Pain\nAbdomen'),
  ChecksymData('Vomiting'),
  ChecksymData('Loss of\nAppetite'),
  ChecksymData('Acidity'),
  ChecksymData('Constipation'),
  ChecksymData('Nausea'),
  ChecksymData('Weakness'),
  ChecksymData('Dizziness'),
  ChecksymData('Boils'),
  ChecksymData('Itching'),
  ChecksymData('Acne'),
  ChecksymData('Dysuria'),
  ChecksymData('Vaginal\nDischarge'),
  ChecksymData('Altered\nSensorium'),
  ChecksymData('Adnexal\nTenderness'),
  ChecksymData('Red/Watery\nEyes'),
  ChecksymData('Blurring\nof Vision'),
  ChecksymData('Injury/\nTrauma'),
  ChecksymData('Bone Pain'),
  ChecksymData('Burns'),
  ChecksymData('Toothache'),
  ChecksymData('Swelling in\nTooth Area'),
  ChecksymData('Pain Ear'),
  ChecksymData('Retroorbital\nPain'),
  ChecksymData('Malaise'),
  ChecksymData('Swelling\nin Joints'),
  ChecksymData('Nasal\nCongestion'),
  ChecksymData('Regurgitation after Meals'),
  ChecksymData('Urine\nUrgency'),
  ChecksymData('Cervical\nTenderness'),
  ChecksymData('Burning\nSensation'),
  ChecksymData('Sticky Eyes'),
  ChecksymData('Bleeding\nGums'),
  //ChecksymData('Increased\nFrequency'),
  //ChecksymData('Swelling'),
  //ChecksymData('Incontinence'),
  // ChecksymData('Redness'),
  // ChecksymData('Papules'),
  //ChecksymData('Polyuria'),
  //ChecksymData('Dysmen-\n-orrhea'),
  //ChecksymData('Insomnia'),
];
