import 'package:guidelines/medicine_data.dart';

final medicineList = [
  MedicineData(
    'Amikacin',
    'Intravenous',
    '15-22.5 mg/Kg/day in 2-3 doses',
    '15 mg/Kg/day q 8-12 hours, max doses 1.5 mg/Kg',
    'Nephrotoxicity, Ototoxicity',
  ),
  MedicineData(
    'Amoxycillin',
    'Oral',
    '20-50 mg/Kg/day, 3-4 Doses',
    '250-500mg q 8 hourly',
    'Fever, rash, diarrhea, abdominal cramps, AST ALT elevation',
  ),
  MedicineData(
    'Amoxycillin- clavunate (co-amoxyclav)',
    'Oral, IV',
    '40mg/kg/day (amoxicillin) in 2 doses 90mg/kg/day if penicillin resistant S. pneumonia suspected\n\nIn otitis media 100mg/kg/day',
    '375mg 8hourly 625-1000mg 12 hourly',
    'Rash, diarrhea, abdominal, AST ALT elevation',
  ),
  MedicineData(
    'Ampicillin',
    'Oral, IV',
    '100-400 mg/kg/day in 4 doses (IV)',
    '500 mg-1gm q 6 hourly',
    'Hypersensitivity reaction, nausea, diarrhea, exfoliative dermatitis, seizures, precipitates infectious mononucleosis rash, interstitial nephritis',
  ),
  MedicineData(
    'Azithromycin',
    'Oral',
    '10 mg/kg/day once daily Enteric fever 20 mg/kg/day once daily',
    '500mg daily',
    'Leukopenia, transient elevation of liver enzymes, renal toxicity',
  ),
  MedicineData(
    'Azetronam',
    'IV',
    '30 - 120mg/kg/day Q 6-8 hourly. In cystic fibrosis max dose 200 mg/kg/day',
    '1-2g q 8 hourly, Max dose 8gm in 24 hours',
    'Rash, Diarrhoea , vomiting, AST, ALT elevation',
  ),
  MedicineData(
    'Benzathine Penicillin',
    'IM',
    '1,200,000 units( >30 Kg) 600,000 units ( <30 Kg)',
    '1.2-2.4 million units/dose',
    'Hypersensitivity and Jarisch Herxheimer reaction, haemolytic anemia, seizures with high doses in renal failure',
  ),
  MedicineData(
    'Cefadroxil',
    'Oral',
    '30 mg/kg/day in 2 Doses',
    '500mg bid or 1 g bid',
    'Rash eosinophilla',
  ),
  MedicineData(
    'Cefazolin',
    'IV',
    '100 mg/kg/day 3-4 divided doses',
    '0.52gm q 6-8 hourly',
    'Leukopenia, eosinophilia, rash, transient elevation of liver enzymes renal toxicity',
  ),
  MedicineData(
    'Cefepime',
    'IV',
    ' ',
    '1-4gm/day 2-3 doses',
    'Same as third generation cephalosporins. Adjust dose in renal failure',
  ),
  MedicineData(
    'Cefixime',
    'Oral',
    '15mg/kg/day in 2 divided doses, 20mg/kg/day in 2 divided doses for enteric fever',
    '400mg/day in 1-2 divided doses',
    'Diarrhoea, Leukopenia, renal toxicity, transient elevation of liver enzymes',
  ),
  MedicineData(
    'Cefotaxime',
    'IV',
    '100mg/kg/day in 3-4 divided doses, 200mg/kg/day in 4 divided doses for meningitis',
    '1-2gm 6-8 hourly',
    'Arrythmia, transient elevation of liver enzymes, renal toxicity',
  ),
  MedicineData(
    'Ceftazidime',
    'IV, IM',
    '75-100mg/kg/day in 3 divided doses 100mg/kg/day in meningitis (IV)',
    '1-2g q 8-12 hourly (IV)',
    'Hypersensitivity reaction, dizziness, rash, diarrhea, colitis, exfoliative dermatitis, thrombocytopenia',
  ),
  MedicineData(
    'Ceftriaxone',
    'IV',
    '50-100 mg/kg/day in 2 divided doses Meningitis 100mg/kg/day in 2 divided doses',
    '1-2gm q 12-24 hourly',
    'Gall bladder sludging, transient elevation of liver enzymes, renal toxicity',
  ),
  MedicineData(
    'Cefuroxime',
    'IV',
    '75-100mg/kg/day in 3 divided doses',
    '750mg- 1.5g q 8 hourly',
    'Leukopenia, eosinophilia, allergic reaction, transient elevation of liver enzymes , renal toxicity',
  ),
  MedicineData(
    'Cefuroxime',
    'Oral',
    '20-30mg/kg/day in 2 divided doses',
    '250-500md bid',
    'Leukopenia, eosinophilia, allergic reaction, transient elevation of liver enzymes , renal toxicity',
  ),
  MedicineData(
    'Cephalexin',
    'Oral',
    '30-40mg/kg/day in 3 divided doses',
    '250-500mg q 8 hourly',
    'Transient neutropenia, AST and ALT elevation, arthralgia, rash, eosinophilia',
  ),
  MedicineData(
    'Chloramphenicol',
    'Oral, IV',
    '75-100mg/kg/day in 4 divided doses. Avoid in infants less than 3 months',
    '50mg/kg/day in 4 divided doses',
    'Bone marrow suppression, aplastic anaemia, grey baby syndrome, hemolysis in G6PD deficiency',
  ),
  MedicineData(
    'Ciprofloxacin',
    'Oral, IV',
    '20-30mg/kg/day in 2 divided doses',
    '250-750mg q 12 hourly',
    'Nausea, vomiting, abdominal discomfort, arthralgia, photosensitivity transient elevation of liver enzymes',
  ),
  MedicineData(
    'Clarithromycin',
    'Oral, IV',
    '15mg/kg/day in 2 divided doses',
    '250-500mg bid',
    'Transient elevation of liver enzymes, renal toxicity, nausea, abdominal cramps',
  ),
  MedicineData(
    'Clindamycin',
    'Oral, IV',
    '40-60mg/kg/day in 3- 4 divided doses',
    '150-300 mg q 6-8 hourly (oral, iv) Severe infections 300-600 mg 8 hourly IV',
    'Diarrhea, nausea, pseudomembranous colitis, skin rash, Erythema multiforme , raised ALT AST, thrombocytopenia, leucopenia',
  ),
  MedicineData(
    'Cloxacillin',
    'Oral, IV',
    '50-100mg/kg/day in 3-4 divided doses. 100-200mg/kg/day divides q 6 hourly',
    '250-500mg/kg/day in 3-4 divided doses 1-2 gram q 6 hourly',
    'Dose related neutropenia, elevated AST, ALT, Cholecystitis interstitial nephritis',
  ),
  MedicineData(
    'Cotrimoxazole',
    'Oral',
    '5-10mg/kg/day in 2 divided doses (5-0 mg trimethoprim) 20mg/kg/day in 4 divided doses in Pneumocystis jirovecii pneumonia',
    '160mg (Trimethoprim) bid',
    'Megaloblastic anaemia, distrurbance, rash, erythema mutliforme major/minor',
  ),
  MedicineData(
    'Ertapenem',
    'IV, IM',
    '3-12 years: 15mg/kg/day twice daily. (not to exceed 1gm/day)',
    '13 years and above 1gm IV infusion/ IM once daily in 3-5 ml of lidocain CI if hypersensitivity to lidocaine/β lactam',
    'Diarrhoea, nausea, vomiting, headache, hallucination, seizures, arrhythmia, pseudomembranous colitis, dose reduction in renal failure',
  ),
  MedicineData(
    'Erythromycin',
    'Oral',
    '40on 4 divided doses',
    '250-500mg q 6 hourly',
    'Arrhythmia Jaundice',
  ),
  MedicineData(
    'Furazolidine',
    'Oral',
    '100mg 3-4 times a day 5mg/kg in 3-4 divides doses (not below one year)',
    '100mg 3-4 times a day',
    'Avoid alcohol, tyramine containing food, Mao inhibitors, Nausea headache, dizziness, fall in BP, urticarial, safety in pregnancy unknown',
  ),
  MedicineData(
    'Gentamicin',
    'IV, IM',
    '5-7.5 mg/kg/day in 2- 3 divided doses',
    '1.3-6 mg/kg/day in 3 divided doses',
    'Nephrotoxicity ototoxicity and optic neuritis',
  ),
  MedicineData(
    'Imipenemcilastin',
    'Oral',
    'Intravenous',
    '500mg once daily',
    'Peripheral and optic neuropathy, thrombocytopenia, hypertension, myelosuppression, colitis',
  ),
  MedicineData(
    'Linezolid',
    'Oral, IV',
    '10mg/kg/dose 6-8 hourly (oral, IV)',
    '400-600 mg q 12 Hourly',
    'Peripheral and optic neuropathy, thrombocytopenia, hypertension, myelosuppression, colitis',
  ),
  MedicineData(
    'Meropenem',
    'IV, Oral',
    '7.5 mg/kg/day/dose (IV) divided doses in meningitis',
    '1.5-3gm/day in 3 divided doses 6gm/day in meningitis',
    'Hypotension, transient elevation of liver enzymes, renal modification in renal failure',
  ),
  MedicineData(
    'Metronidazole',
    'IV, Oral',
    '7.5 mg/kg/day dose 3 times/day 30-50mg/kg/day in 3 divided doses for liver abscess',
    '500-700 q 8 hourly',
    'Nausea, metallic taste, disulfuran like reaction with alcohol, peripheral neuropathy',
  ),
  MedicineData(
    'Nalidixic acid',
    'Oral',
    '8 mg/kg/day in 2 divided doses',
    '1gm 4 times/day',
    'Hepatotoxicity, myalgia, leukopenia, vertigo, rash, dizziness, pseudotumor cerebri, seizure, avoid in G6PD deficiency',
  ),
  MedicineData(
    'Nitofurantoin',
    'Oral',
    '8 mg/kg/day in 2 divided doses',
    '50-100 mg q 6 hourly (5-7mg/kg/day in 4 divided doses max dose 400mg)',
    'Discoloration of urine, vertigo, rash, methemoglobinemia, cholestatic jaundice, hepatocellular damage and neuropathy. Avoid at term and labour',
  ),
  MedicineData(
    'Norfloxacin',
    'Oral',
    '20-30 mg/kg/day in 2 divided doses',
    '200-400 mg twice daily',
    'Same as quinolones',
  ),
  MedicineData(
    'Ofloxacin',
    'Oral, IV',
    '20 mg/kg/day in 2 divided doses',
    '200-400 q 12 hourly',
    'Leukopenia, transient of liver enzymes, renal toxicity. May precipitate psychosis/seizures,photosensitivity',
  ),
  MedicineData(
    'Penicillin G',
    'Oral, Intravenous',
    '50,000units/kg/ dose 6 hourly (Oral). 200,000-400,000 units/kg/day in 4 divided doses (IV)',
    '2-24 million units day in divided doses q 4-6 hours (IV)',
    'Hypersensitivity reaction like anaphylaxis rare. nonfatal reactions are like serum sickness, rash contact dermatitis seen in 1 in 1000 adults. Jarisch Herxheimer reaction, haemolytic anaemia with high Doses',
  ),
  MedicineData(
    'Penicillin V',
    'Oral',
    '20-50 mg/kg/day in 4 divided doses',
    '250-500 mg every 6-8 hourly',
    'Rash, haemolytic anaemia interstitial nephritis, seizure with high doses',
  ),
  MedicineData(
    'Piperacillin-Tazobactum',
    'IV',
    '200-400mg/kg/day in 3-4 divided doses',
    '4.5 gm q 8hourly',
    'Leukopenia, transient elevation of liver enzymes, renal toxicity',
  ),
  MedicineData(
    'Teicoplanin',
    'IV, IM',
    '10mg/kg/day /dose every 12 hours for 3 doses the 10mg/kg/day once Daily',
    '400mg once daily (6- 30mg/kg/day)',
    'Hypersensitivity reactions, rash, less nephrotoxic as compares to Vancomycin',
  ),
  MedicineData(
    'Tigecycline',
    'IV',
    'Above 10 years',
    '100mg followed by 50mg every 12 hurly infusion over 30-60 minutes.',
    'Nausea, vomiting, allergic reactions, photosensitivity, pseudo tumor cerebri, pancreatitis. No dose adjustment to renal failure',
  ),
  MedicineData(
    'Vancomycin',
    'IV',
    '40-60 mg/kg/day in 3-4 divided doses',
    '0.5gm q 6 hourly or 1gm q 12 hourly',
    'Red man syndrome, oto-toxicity, Nephrotoxicity',
  ),
];
